services:
  postgres:
    image: postgres:16
    container_name: mldz_creator_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mldz_creator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - mldz_creator_pg:/var/lib/postgresql/data

volumes:
  mldz_creator_pg:
