apiVersion: v1
kind: Service
metadata:
  name: creatorapp-backend-api
spec:
  selector:
    app.kubernetes.io/name: creatorapp-backend
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
