apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: creatorapp
resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - api-service.yaml
  - hpa-api.yaml
  - pdb-api.yaml
  - scaledobject-worker.yaml
  - podmonitor.yaml
  - gateway.yaml
