apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: creatorapp-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: creatorapp-backend
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
