apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: creatorapp-backend-worker
spec:
  scaleTargetRef:
    name: creatorapp-backend-worker
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 4
  maxReplicaCount: 1000
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring:9090
        metricName: background_jobs_due_pending
        threshold: "100"
        query: sum(background_jobs_due_pending)
